USE academico;

-- Se limpia antes de comenzar
DROP ROLE IF EXISTS vicerrectoriasede;
DROP ROLE IF EXISTS secretariageneral;
DROP ROLE IF EXISTS direccioncurricularpregrado;
DROP ROLE IF EXISTS direccioncurricularposgrado;
DROP ROLE IF EXISTS direccioninformacionacademica;
DROP ROLE IF EXISTS direccionsedespresencianal;
DROP ROLE IF EXISTS divisionderegistroymatricula;
DROP ROLE IF EXISTS decanaturafacultad;
DROP ROLE IF EXISTS secretariafacultad;
DROP ROLE IF EXISTS profesor;
DROP ROLE IF EXISTS estudiante;

-- Se crean los 11 roles definidos en la matriz de acceso
CREATE ROLE vicerrectoriasede;
CREATE ROLE secretariageneral;
CREATE ROLE direccioncurricularpregrado;
CREATE ROLE direccioncurricularposgrado;
CREATE ROLE direccioninformacionacademica;
CREATE ROLE direccionsedespresencianal;
CREATE ROLE divisionderegistroymatricula;
CREATE ROLE decanaturafacultad;
CREATE ROLE secretariafacultad;
CREATE ROLE profesor;
CREATE ROLE estudiante;

-- Asignación de permisos a Vicerrectoria de Sede 
GRANT SELECT ON academico.persona TO vicerrectoriasede;
GRANT SELECT ON academico.vinculado TO vicerrectoriasede;
GRANT SELECT ON academico.responsable TO vicerrectoriasede;
GRANT SELECT ON academico.profesor TO vicerrectoriasede;
GRANT SELECT ON academico.residencia TO vicerrectoriasede;
GRANT SELECT ON academico.estudiante TO vicerrectoriasede;
GRANT SELECT ON academico.estudiante_has_responsable TO vicerrectoriasede;
GRANT SELECT ON academico.sede TO vicerrectoriasede;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.facultad TO vicerrectoriasede;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.departamento TO vicerrectoriasede;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.programa TO vicerrectoriasede;
GRANT SELECT ON academico.asignatura TO vicerrectoriasede;
GRANT SELECT ON academico.prerrequisito TO vicerrectoriasede;
GRANT SELECT ON academico.grupo TO vicerrectoriasede;
GRANT SELECT ON academico.grupo_info TO vicerrectoriasede;
GRANT SELECT ON academico.historia_academica TO vicerrectoriasede;
GRANT SELECT ON academico.cita_por_historia_Academica TO vicerrectoriasede;
GRANT SELECT ON academico.inscripcion TO vicerrectoriasede;
GRANT SELECT ON academico.calificacion TO vicerrectoriasede;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.ceremonia_grado TO vicerrectoriasede;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.solicitud_inscripcion_grado TO vicerrectoriasede;
GRANT SELECT ON academico.malla TO vicerrectoriasede;
GRANT SELECT ON academico.agrupacion_asignaturas TO vicerrectoriasede;
GRANT SELECT ON academico.asignatura_asociada TO vicerrectoriasede;
GRANT SELECT, UPDATE ON academico.solicitud_sobrecupo TO vicerrectoriasede;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_fac_pro_sed TO vicerrectoriasede;
GRANT SELECT ON academico.vw_estudiantes_act TO vicerrectoriasede;
GRANT SELECT ON academico.vw_docentes_act TO vicerrectoriasede;
GRANT SELECT ON academico.vw_estudiantes_pregrado TO vicerrectoriasede;
GRANT SELECT ON academico.vw_estudiantes_posgrado TO vicerrectoriasede;
GRANT SELECT ON academico.vw_estudiantes_doble TO vicerrectoriasede;
GRANT SELECT ON academico.vw_estudiantes_reserva TO vicerrectoriasede;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_ceremonia_grado TO vicerrectoriasede;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_solicitud_inscripcion_grado TO vicerrectoriasede;
GRANT SELECT ON academico.vw_datos_personales_estudiante TO vicerrectoriasede;
GRANT SELECT ON academico.vw_datos_personales_profesor TO vicerrectoriasede;
GRANT SELECT ON academico.vw_buscador_cursos TO vicerrectoriasede;
GRANT SELECT ON academico.vw_asignatura_grupos TO vicerrectoriasede;
GRANT SELECT ON academico.vw_grupos_disponibles TO vicerrectoriasede;
GRANT SELECT ON academico.vw_grupos_disponibles2 TO vicerrectoriasede;
GRANT SELECT ON academico.vw_grupos_disponibles2 TO vicerrectoriasede;
GRANT EXECUTE ON PROCEDURE academico.sp_buscador_cursos TO vicerrectoriasede;
GRANT EXECUTE ON PROCEDURE academico.sp_facultades_por_sede TO vicerrectoriasede;
GRANT EXECUTE ON PROCEDURE academico.sp_programas_por_facultades TO vicerrectoriasede;
GRANT EXECUTE ON PROCEDURE academico.sp_seleccionar_rol TO vicerrectoriasede;
GRANT EXECUTE ON FUNCTION academico.obtenerSemestreActual TO vicerrectoriasede;
GRANT EXECUTE ON FUNCTION academico.aprobacion TO vicerrectoriasede;
GRANT EXECUTE ON FUNCTION academico.obligatorio TO vicerrectoriasede;

-- Asignación de permisos a Secretaría General 
GRANT SELECT ON academico.persona TO secretariageneral;
GRANT SELECT ON academico.vinculado TO secretariageneral;
GRANT SELECT ON academico.responsable TO secretariageneral;
GRANT SELECT ON academico.profesor TO secretariageneral;
GRANT SELECT ON academico.residencia TO secretariageneral;
GRANT SELECT ON academico.estudiante TO secretariageneral;
GRANT SELECT ON academico.estudiante_has_responsable TO secretariageneral;
GRANT SELECT ON academico.sede TO secretariageneral;
GRANT SELECT ON academico.facultad TO secretariageneral;
GRANT SELECT ON academico.departamento TO secretariageneral;
GRANT SELECT, UPDATE ON academico.programa TO secretariageneral;
GRANT SELECT, INSERT, UPDATE ON academico.asignatura TO secretariageneral;
GRANT SELECT, INSERT, UPDATE ON academico.prerrequisito TO secretariageneral;
GRANT SELECT, INSERT, UPDATE ON academico.grupo TO secretariageneral;
GRANT SELECT, INSERT, UPDATE ON academico.grupo_info TO secretariageneral;
GRANT SELECT ON academico.historia_academica TO secretariageneral;
GRANT SELECT, INSERT, UPDATE ON academico.cita_por_historia_academica TO secretariageneral;
GRANT SELECT, INSERT, UPDATE ON academico.inscripcion TO secretariageneral;
GRANT SELECT ON academico.calificacion TO secretariageneral;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.ceremonia_grado TO secretariageneral;
GRANT SELECT, INSERT, UPDATE ON academico.solicitud_inscripcion_grado TO secretariageneral;
GRANT SELECT ON academico.malla TO secretariageneral;
GRANT SELECT ON academico.agrupacion_asignaturas TO secretariageneral;
GRANT SELECT ON academico.asignatura_asociada TO secretariageneral;
GRANT SELECT, UPDATE ON academico.solicitud_sobrecupo TO secretariageneral;
GRANT SELECT, INSERT, UPDATE ON academico.vw_fac_pro_sed TO secretariageneral;
GRANT SELECT, UPDATE ON academico.vw_pro_asignatura TO secretariageneral;
GRANT SELECT, UPDATE ON academico.vw_asignatura_prereq TO secretariageneral;
GRANT SELECT, UPDATE ON academico.vw_estudiantes_act TO secretariageneral;
GRANT SELECT, INSERT, UPDATE ON academico.vw_historia_academica TO secretariageneral;
GRANT SELECT ON academico.vw_calificacion_grupo TO secretariageneral;
GRANT SELECT ON academico.vw_calificacion_asig TO secretariageneral;
GRANT SELECT ON academico.vw_cita_inscrip TO secretariageneral;
GRANT SELECT ON academico.vw_docentes_act TO secretariageneral;
GRANT SELECT ON academico.vw_estudiantes_pregrado TO secretariageneral;
GRANT SELECT ON academico.vw_estudiantes_posgrado TO secretariageneral;
GRANT SELECT ON academico.vw_estudiantes_doble TO secretariageneral;
GRANT SELECT ON academico.vw_estudiantes_reserva TO secretariageneral;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_ceremonia_grado TO secretariageneral;
GRANT SELECT, INSERT, UPDATE ON academico.vw_solicitud_inscripcion_grado TO secretariageneral;
GRANT SELECT ON academico.vw_datos_personales_estudiante TO secretariageneral;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_datos_personales_profesor TO secretariageneral;
GRANT SELECT ON academico.vw_buscador_cursos TO secretariageneral;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_asignatura_grupos TO secretariageneral;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_grupos_disponibles TO secretariageneral;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_grupos_disponibles2 TO secretariageneral;
GRANT EXECUTE ON PROCEDURE academico.sp_buscador_cursos TO secretariageneral;
GRANT EXECUTE ON PROCEDURE academico.sp_facultades_por_sede TO secretariageneral;
GRANT EXECUTE ON PROCEDURE academico.sp_programas_por_facultades TO secretariageneral;
GRANT EXECUTE ON PROCEDURE academico.sp_traslado_programa TO secretariageneral;
GRANT EXECUTE ON PROCEDURE academico.sp_seleccionar_rol TO secretariageneral;
GRANT EXECUTE ON FUNCTION academico.obtenerSemestreActual TO secretariageneral;
GRANT EXECUTE ON FUNCTION academico.aprobacion TO secretariageneral;
GRANT EXECUTE ON FUNCTION academico.obligatorio TO secretariageneral;

-- Asignación de permisos a Dirección Curricular de Pregrado
GRANT SELECT ON academico.persona TO direccioncurricularpregrado;
GRANT SELECT ON academico.vinculado TO direccioncurricularpregrado;
GRANT SELECT ON academico.responsable TO direccioncurricularpregrado;
GRANT SELECT ON academico.profesor TO direccioncurricularpregrado;
GRANT SELECT ON academico.residencia TO direccioncurricularpregrado;
GRANT SELECT ON academico.estudiante TO direccioncurricularpregrado;
GRANT SELECT ON academico.estudiante_has_responsable TO direccioncurricularpregrado;
GRANT SELECT ON academico.sede TO direccioncurricularpregrado;
GRANT SELECT ON academico.facultad TO direccioncurricularpregrado;
GRANT SELECT ON academico.departamento TO direccioncurricularpregrado;
GRANT SELECT ON academico.programa TO direccioncurricularpregrado;
GRANT SELECT ON academico.asignatura TO direccioncurricularpregrado;
GRANT SELECT ON academico.prerrequisito TO direccioncurricularpregrado;
GRANT SELECT ON academico.grupo TO direccioncurricularpregrado;
GRANT SELECT ON academico.grupo_info TO direccioncurricularpregrado;
GRANT SELECT ON academico.historia_academica TO direccioncurricularpregrado;
GRANT SELECT ON academico.cita_por_historia_academica TO direccioncurricularpregrado;
GRANT SELECT ON academico.inscripcion TO direccioncurricularpregrado;
GRANT SELECT ON academico.calificacion TO direccioncurricularpregrado;
GRANT SELECT ON academico.ceremonia_grado TO direccioncurricularpregrado;
GRANT SELECT ON academico.solicitud_inscripcion_grado TO direccioncurricularpregrado;
GRANT SELECT ON academico.malla TO direccioncurricularpregrado;
GRANT SELECT ON academico.agrupacion_asignaturas TO direccioncurricularpregradol;
GRANT SELECT ON academico.asignatura_asociada TO direccioncurricularpregrado;
GRANT SELECT, UPDATE ON academico.solicitud_sobrecupo TO direccioncurricularpregrado;
GRANT SELECT, INSERT, UPDATE ON academico.vw_fac_pro_sed TO direccioncurricularpregrado;
GRANT SELECT ON academico.vw_pro_asignatura TO direccioncurricularpregrado;
GRANT SELECT ON academico.vw_asignatura_prereq TO direccioncurricularpregrado;
GRANT SELECT, UPDATE ON academico.vw_estudiantes_act TO direccioncurricularpregrado;
GRANT SELECT ON academico.vw_historia_academica TO direccioncurricularpregrado;
GRANT SELECT ON academico.vw_calificacion_grupo TO direccioncurricularpregrado;
GRANT SELECT ON academico.vw_calificacion_asig TO direccioncurricularpregrado;
GRANT SELECT ON academico.vw_cita_inscrip TO direccioncurricularpregrado;
GRANT SELECT ON academico.vw_docentes_act TO direccioncurricularpregrado;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_estudiantes_pregrado TO direccioncurricularpregrado;
GRANT SELECT ON academico.vw_ceremonia_grado TO direccioncurricularpregrado;
GRANT SELECT ON academico.vw_solicitud_inscripcion_grado TO direccioncurricularpregrado;
GRANT SELECT ON academico.vw_datos_personales_estudiante TO direccioncurricularpregrado;
GRANT SELECT ON academico.vw_datos_personales_profesor TO direccioncurricularpregrado;
GRANT SELECT ON academico.vw_buscador_cursos TO direccioncurricularpregrado;
GRANT SELECT ON academico.vw_asignatura_grupos TO direccioncurricularpregrado;
GRANT SELECT ON academico.vw_grupos_disponibles TO direccioncurricularpregrado;
GRANT SELECT ON academico.vw_grupos_disponibles2 TO direccioncurricularpregrado;
GRANT EXECUTE ON PROCEDURE academico.sp_buscador_cursos TO direccioncurricularpregrado;
GRANT EXECUTE ON PROCEDURE academico.sp_facultades_por_sede TO direccioncurricularpregrado;
GRANT EXECUTE ON PROCEDURE academico.sp_programas_por_facultades TO direccioncurricularpregrado;
GRANT EXECUTE ON PROCEDURE academico.sp_insertar_calificacion TO direccioncurricularpregrado;
GRANT EXECUTE ON PROCEDURE academico.sp_seleccionar_rol TO direccioncurricularpregrado;
GRANT EXECUTE ON FUNCTION academico.obtenerSemestreActual TO direccioncurricularpregrado;
GRANT EXECUTE ON FUNCTION academico.aprobacion TO direccioncurricularpregrado;
GRANT EXECUTE ON FUNCTION academico.obligatorio TO direccioncurricularpregrado;

-- Asignación de permisos a Dirección Curricular de Posgrado
GRANT SELECT ON academico.persona TO direccioncurricularposgrado;
GRANT SELECT ON academico.vinculado TO direccioncurricularposgrado;
GRANT SELECT ON academico.responsable TO direccioncurricularposgrado;
GRANT SELECT ON academico.profesor TO direccioncurricularposgrado;
GRANT SELECT ON academico.residencia TO direccioncurricularposgrado;
GRANT SELECT ON academico.estudiante TO direccioncurricularposgrado;
GRANT SELECT ON academico.estudiante_has_responsable TO direccioncurricularposgrado;
GRANT SELECT ON academico.sede TO direccioncurricularposgrado;
GRANT SELECT ON academico.facultad TO direccioncurricularposgrado;
GRANT SELECT ON academico.departamento TO direccioncurricularposgrado;
GRANT SELECT ON academico.programa TO direccioncurricularposgrado;
GRANT SELECT ON academico.asignatura TO direccioncurricularposgrado;
GRANT SELECT ON academico.prerrequisito TO direccioncurricularposgrado;
GRANT SELECT ON academico.grupo TO direccioncurricularposgrado;
GRANT SELECT ON academico.grupo_info TO direccioncurricularposgrado;
GRANT SELECT ON academico.historia_academica TO direccioncurricularposgrado;
GRANT SELECT ON academico.cita_por_historia_academica TO direccioncurricularposgrado;
GRANT SELECT ON academico.inscripcion TO direccioncurricularposgrado;
GRANT SELECT ON academico.calificacion TO direccioncurricularposgrado;
GRANT SELECT ON academico.ceremonia_grado TO direccioncurricularposgrado;
GRANT SELECT ON academico.solicitud_inscripcion_grado TO direccioncurricularposgrado;
GRANT SELECT ON academico.malla TO direccioncurricularposgrado;
GRANT SELECT ON academico.agrupacion_asignaturas TO direccioncurricularposgrado;
GRANT SELECT ON academico.asignatura_asociada TO direccioncurricularposgrado;
GRANT SELECT, UPDATE ON academico.solicitud_sobrecupo TO direccioncurricularposgrado;
GRANT SELECT, INSERT, UPDATE ON academico.vw_fac_pro_sed TO direccioncurricularposgrado;
GRANT SELECT ON academico.vw_pro_asignatura TO direccioncurricularposgrado;
GRANT SELECT ON academico.vw_asignatura_prereq TO direccioncurricularposgrado;
GRANT SELECT, UPDATE ON academico.vw_estudiantes_act TO direccioncurricularposgrado;
GRANT SELECT ON academico.vw_historia_academica TO direccioncurricularposgrado;
GRANT SELECT ON academico.vw_calificacion_grupo TO direccioncurricularposgrado;
GRANT SELECT ON academico.vw_calificacion_asig TO direccioncurricularposgrado;
GRANT SELECT ON academico.vw_cita_inscrip TO direccioncurricularposgrado;
GRANT SELECT ON academico.vw_docentes_act TO direccioncurricularposgrado;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_estudiantes_posgrado TO direccioncurricularposgrado;
GRANT SELECT ON academico.vw_ceremonia_grado TO direccioncurricularposgrado;
GRANT SELECT ON academico.vw_solicitud_inscripcion_grado TO direccioncurricularposgrado;
GRANT SELECT ON academico.vw_datos_personales_estudiante TO direccioncurricularposgrado;
GRANT SELECT ON academico.vw_datos_personales_profesor TO direccioncurricularposgrado;
GRANT SELECT ON academico.vw_buscador_cursos TO direccioncurricularposgrado;
GRANT SELECT ON academico.vw_asignatura_grupos TO direccioncurricularposgrado;
GRANT SELECT ON academico.vw_grupos_disponibles TO direccioncurricularposgrado;
GRANT SELECT ON academico.vw_grupos_disponibles2 TO direccioncurricularposgrado;
GRANT EXECUTE ON PROCEDURE academico.sp_buscador_cursos TO direccioncurricularposgrado;
GRANT EXECUTE ON PROCEDURE academico.sp_facultades_por_sede TO direccioncurricularposgrado;
GRANT EXECUTE ON PROCEDURE academico.sp_programas_por_facultades TO direccioncurricularposgrado;
GRANT EXECUTE ON PROCEDURE academico.sp_seleccionar_rol TO direccioncurricularposgrado;
GRANT EXECUTE ON FUNCTION academico.obtenerSemestreActual TO direccioncurricularposgrado;
GRANT EXECUTE ON FUNCTION academico.aprobacion TO direccioncurricularposgrado;
GRANT EXECUTE ON FUNCTION academico.obligatorio TO direccioncurricularposgrado;

-- Asignación de permisos a Dirección Información Académica
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.persona TO direccioninformacionacademica;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vinculado TO direccioninformacionacademica;
GRANT SELECT, DELETE ON academico.responsable TO direccioninformacionacademica;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.profesor TO direccioninformacionacademica;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.residencia TO direccioninformacionacademica;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.estudiante TO direccioninformacionacademica;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.estudiante_has_responsable TO direccioninformacionacademica;
GRANT SELECT ON academico.sede TO direccioninformacionacademica;
GRANT SELECT ON academico.facultad TO direccioninformacionacademica;
GRANT SELECT ON academico.departamento TO direccioninformacionacademica;
GRANT SELECT ON academico.programa TO direccioninformacionacademica;
GRANT SELECT ON academico.asignatura TO direccioninformacionacademica;
GRANT SELECT ON academico.prerrequisito TO direccioninformacionacademica;
GRANT SELECT ON academico.grupo TO direccioninformacionacademica;
GRANT SELECT ON academico.grupo_info TO direccioninformacionacademica;
GRANT SELECT ON academico.historia_academica TO direccioninformacionacademica;
GRANT SELECT ON academico.cita_por_historia_academica TO direccioninformacionacademica;
GRANT SELECT ON academico.inscripcion TO direccioninformacionacademica;
GRANT SELECT ON academico.calificacion TO direccioninformacionacademica;
GRANT SELECT ON academico.solicitud_sobrecupo TO direccioninformacionacademica;
GRANT SELECT ON academico.vw_fac_pro_sed TO direccioninformacionacademica;
GRANT SELECT ON academico.vw_pro_asignatura TO direccioninformacionacademica;
GRANT SELECT ON academico.vw_asignatura_prereq TO direccioninformacionacademica;
GRANT SELECT ON academico.vw_estudiantes_act TO direccioninformacionacademica;
GRANT SELECT ON academico.vw_historia_academica TO direccioninformacionacademica;
GRANT SELECT ON academico.vw_calificacion_grupo TO direccioninformacionacademica;
GRANT SELECT ON academico.vw_calificacion_asig TO direccioninformacionacademica;
GRANT SELECT ON academico.vw_cita_inscrip TO direccioninformacionacademica;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_docentes_act TO direccioninformacionacademica;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_estudiantes_pregrado TO direccioninformacionacademica;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_estudiantes_posgrado TO direccioninformacionacademica;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_estudiantes_doble TO direccioninformacionacademica;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_estudiantes_reserva TO direccioninformacionacademica;
GRANT SELECT ON academico.vw_datos_personales_estudiante TO direccioninformacionacademica;
GRANT SELECT ON academico.vw_datos_personales_profesor TO direccioninformacionacademica;
GRANT SELECT ON academico.vw_buscador_cursos TO direccioninformacionacademica;
GRANT SELECT ON academico.vw_asignatura_grupos TO direccioninformacionacademica;
GRANT SELECT ON academico.vw_grupos_disponibles TO direccioninformacionacademica;
GRANT SELECT ON academico.vw_grupos_disponibles2 TO direccioninformacionacademica;
GRANT EXECUTE ON PROCEDURE academico.sp_buscador_cursos TO direccioninformacionacademica;
GRANT EXECUTE ON PROCEDURE academico.sp_facultades_por_sede TO direccioninformacionacademica;
GRANT EXECUTE ON PROCEDURE academico.sp_programas_por_facultades TO direccioninformacionacademica;
GRANT EXECUTE ON PROCEDURE academico.sp_nuevo_grupo TO direccioninformacionacademica;
GRANT EXECUTE ON PROCEDURE academico.sp_borrar_grupo TO direccioninformacionacademica;
GRANT EXECUTE ON PROCEDURE academico.sp_seleccionar_rol TO direccioninformacionacademica;
GRANT EXECUTE ON FUNCTION academico.obtenerSemestreActual TO direccioninformacionacademica;
GRANT EXECUTE ON FUNCTION academico.aprobacion TO direccioninformacionacademica;
GRANT EXECUTE ON FUNCTION academico.obligatorio TO direccioninformacionacademica;

-- Asignación de permisos a Dirección de Sedes de Presencia Nacional 
GRANT SELECT ON academico.persona TO direccionsedespresencianal;
GRANT SELECT ON academico.vinculado TO direccionsedespresencianal;
GRANT SELECT ON academico.responsable TO direccionsedespresencianal;
GRANT SELECT ON academico.profesor TO direccionsedespresencianal;
GRANT SELECT ON academico.residencia TO direccionsedespresencianal;
GRANT SELECT ON academico.estudiante TO direccionsedespresencianal;
GRANT SELECT ON academico.estudiante_has_responsable TO direccionsedespresencianal;
GRANT SELECT ON academico.sede TO direccionsedespresencianal;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.facultad TO direccionsedespresencianal;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.departamento TO direccionsedespresencianal;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.programa TO direccionsedespresencianal;
GRANT SELECT ON academico.asignatura TO direccionsedespresencianal;
GRANT SELECT ON academico.prerrequisito TO direccionsedespresencianal;
GRANT SELECT ON academico.grupo TO direccionsedespresencianal;
GRANT SELECT ON academico.grupo_info TO direccionsedespresencianal;
GRANT SELECT ON academico.historia_academica TO direccionsedespresencianal;
GRANT SELECT ON academico.cita_por_historia_academica TO direccionsedespresencianal;
GRANT SELECT ON academico.inscripcion TO direccionsedespresencianal;
GRANT SELECT ON academico.calificacion TO direccionsedespresencianal;
GRANT SELECT ON academico.ceremonia_grado TO direccionsedespresencianal;
GRANT SELECT ON academico.solicitud_inscripcion_grado TO direccionsedespresencianal;
GRANT SELECT ON academico.malla TO direccionsedespresencianal;
GRANT SELECT ON academico.agrupacion_asignaturas TO direccionsedespresencianal;
GRANT SELECT ON academico.asignatura_asociada TO direccionsedespresencianal;
GRANT SELECT ON academico.solicitud_sobrecupo TO direccionsedespresencianal;
GRANT SELECT, INSERT, UPDATE ON academico.vw_fac_pro_sed TO direccionsedespresencianal;
GRANT SELECT ON academico.vw_estudiantes_act TO direccionsedespresencianal;
GRANT SELECT ON academico.vw_docentes_act TO direccionsedespresencianal;
GRANT SELECT ON academico.vw_estudiantes_pregrado TO direccionsedespresencianal;
GRANT SELECT ON academico.vw_estudiantes_posgrado TO direccionsedespresencianal;
GRANT SELECT ON academico.vw_estudiantes_doble TO direccionsedespresencianal;
GRANT SELECT ON academico.vw_estudiantes_reserva TO direccionsedespresencianal;
GRANT SELECT ON academico.vw_datos_personales_estudiante TO direccionsedespresencianal;
GRANT SELECT ON academico.vw_datos_personales_profesor TO direccionsedespresencianal;
GRANT SELECT ON academico.vw_buscador_cursos TO direccionsedespresencianal;
GRANT SELECT ON academico.vw_asignatura_grupos TO direccionsedespresencianal;
GRANT SELECT ON academico.vw_grupos_disponibles TO direccionsedespresencianal;
GRANT SELECT ON academico.vw_grupos_disponibles2 TO direccionsedespresencianal;
GRANT EXECUTE ON PROCEDURE academico.sp_buscador_cursos TO direccionsedespresencianal;
GRANT EXECUTE ON PROCEDURE academico.sp_facultades_por_sede TO direccionsedespresencianal;
GRANT EXECUTE ON PROCEDURE academico.sp_programas_por_facultades TO direccionsedespresencianal;
GRANT EXECUTE ON PROCEDURE academico.sp_seleccionar_rol TO direccionsedespresencianal;
GRANT EXECUTE ON FUNCTION academico.obtenerSemestreActual TO direccionsedespresencianal;
GRANT EXECUTE ON FUNCTION academico.aprobacion TO direccionsedespresencianal;
GRANT EXECUTE ON FUNCTION academico.obligatorio TO direccionsedespresencianal;

-- Asignación de permisos a División de Registro y Matrícula
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.persona TO divisionderegistroymatricula;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vinculado TO divisionderegistroymatricula;
GRANT SELECT, DELETE ON academico.responsable TO divisionderegistroymatricula;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.estudiante TO divisionderegistroymatricula;
GRANT SELECT ON academico.estudiante_has_responsable TO divisionderegistroymatricula;
GRANT SELECT ON academico.sede TO divisionderegistroymatricula;
GRANT SELECT ON academico.facultad TO divisionderegistroymatricula;
GRANT SELECT ON academico.departamento TO divisionderegistroymatricula;
GRANT SELECT ON academico.programa TO divisionderegistroymatricula;
GRANT SELECT ON academico.asignatura TO divisionderegistroymatricula;
GRANT SELECT ON academico.prerrequisito TO divisionderegistroymatricula;
GRANT SELECT ON academico.grupo TO divisionderegistroymatricula;
GRANT SELECT ON academico.grupo_info TO divisionderegistroymatricula;
GRANT SELECT ON academico.historia_academica TO divisionderegistroymatricula;
GRANT SELECT ON academico.cita_por_historia_academica TO divisionderegistroymatricula;
GRANT SELECT ON academico.inscripcion TO divisionderegistroymatricula;
GRANT SELECT ON academico.calificacion TO divisionderegistroymatricula;
GRANT SELECT ON academico.vw_fac_pro_sed TO divisionderegistroymatricula;
GRANT SELECT ON academico.vw_pro_asignatura TO divisionderegistroymatricula;
GRANT SELECT ON academico.vw_asignatura_prereq TO divisionderegistroymatricula;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_estudiantes_act TO divisionderegistroymatricula;
GRANT SELECT ON academico.vw_historia_academica TO divisionderegistroymatricula;
GRANT SELECT ON academico.vw_calificacion_grupo TO divisionderegistroymatricula;
GRANT SELECT ON academico.vw_calificacion_asig TO divisionderegistroymatricula;
GRANT SELECT ON academico.vw_cita_inscrip TO divisionderegistroymatricula;
GRANT SELECT ON academico.vw_docentes_act TO divisionderegistroymatricula;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_estudiantes_pregrado TO divisionderegistroymatricula;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_estudiantes_posgrado TO divisionderegistroymatricula;
GRANT SELECT ON academico.vw_estudiantes_doble TO divisionderegistroymatricula;
GRANT SELECT ON academico.vw_estudiantes_reserva TO divisionderegistroymatricula;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_datos_personales_estudiante TO divisionderegistroymatricula;
GRANT SELECT ON academico.vw_datos_personales_profesor TO divisionderegistroymatricula;
GRANT SELECT ON academico.vw_buscador_cursos TO divisionderegistroymatricula;
GRANT SELECT ON academico.vw_asignatura_grupos TO divisionderegistroymatricula;
GRANT SELECT ON academico.vw_grupos_disponibles TO divisionderegistroymatricula;
GRANT SELECT ON academico.vw_grupos_disponibles2 TO divisionderegistroymatricula;
GRANT EXECUTE ON PROCEDURE academico.sp_buscador_cursos TO divisionderegistroymatricula;
GRANT EXECUTE ON PROCEDURE academico.sp_facultades_por_sede TO divisionderegistroymatricula;
GRANT EXECUTE ON PROCEDURE academico.sp_programas_por_facultades TO divisionderegistroymatricula;
GRANT EXECUTE ON PROCEDURE academico.sp_generate_historia_nueva TO divisionderegistroymatricula;
GRANT EXECUTE ON PROCEDURE academico.sp_generate_historias TO divisionderegistroymatricula;
GRANT EXECUTE ON PROCEDURE academico.sp_seleccionar_rol TO divisionderegistroymatricula;
GRANT EXECUTE ON FUNCTION academico.obtenerSemestreActual TO divisionderegistroymatricula;
GRANT EXECUTE ON FUNCTION academico.aprobacion TO divisionderegistroymatricula;
GRANT EXECUTE ON FUNCTION academico.obligatorio TO divisionderegistroymatricula;

-- Asignación de permisos a Decanatura Facultad
GRANT SELECT ON academico.persona TO decanaturafacultad;
GRANT SELECT ON academico.vinculado TO decanaturafacultad;
GRANT SELECT ON academico.responsable TO decanaturafacultad;
GRANT SELECT ON academico.profesor TO decanaturafacultad;
GRANT SELECT ON academico.residencia TO decanaturafacultad;
GRANT SELECT ON academico.estudiante TO decanaturafacultad;
GRANT SELECT ON academico.estudiante_has_responsable TO decanaturafacultad;
GRANT SELECT ON academico.sede TO decanaturafacultad;
GRANT SELECT ON academico.facultad TO decanaturafacultad;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.departamento TO decanaturafacultad;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.programa TO decanaturafacultad;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.asignatura TO decanaturafacultad;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.prerrequisito TO decanaturafacultad;
GRANT SELECT ON academico.grupo TO decanaturafacultad;
GRANT SELECT ON academico.grupo_info TO decanaturafacultad;
GRANT SELECT ON academico.historia_academica TO decanaturafacultad;
GRANT SELECT ON academico.cita_por_historia_academica TO decanaturafacultad;
GRANT SELECT ON academico.inscripcion TO decanaturafacultad;
GRANT SELECT ON academico.calificacion TO decanaturafacultad;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.ceremonia_grado TO decanaturafacultad;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.solicitud_inscripcion_grado TO decanaturafacultad;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.malla TO decanaturafacultad;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.agrupacion_asignaturas TO decanaturafacultad;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.asignatura_asociada TO decanaturafacultad;
GRANT SELECT, UPDATE ON academico.solicitud_sobrecupo TO decanaturafacultad;
GRANT SELECT, INSERT, UPDATE ON academico.vw_fac_pro_sed TO decanaturafacultad;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_pro_asignatura TO decanaturafacultad;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_asignatura_prereq TO decanaturafacultad;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_estudiantes_act TO decanaturafacultad;
GRANT SELECT ON academico.vw_historia_academica TO decanaturafacultad;
GRANT SELECT ON academico.vw_calificacion_grupo TO decanaturafacultad;
GRANT SELECT ON academico.vw_calificacion_asig TO decanaturafacultad;
GRANT SELECT ON academico.vw_cita_inscrip TO decanaturafacultad;
GRANT SELECT ON academico.vw_docentes_act TO decanaturafacultad;
GRANT SELECT ON academico.vw_estudiantes_pregrado TO decanaturafacultad;
GRANT SELECT ON academico.vw_estudiantes_posgrado TO decanaturafacultad;
GRANT SELECT ON academico.vw_estudiantes_doble TO decanaturafacultad;
GRANT SELECT ON academico.vw_estudiantes_reserva TO decanaturafacultad;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_ceremonia_grado TO decanaturafacultad;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_solicitud_inscripcion_grado TO decanaturafacultad;
GRANT SELECT ON academico.vw_datos_personales_estudiante TO decanaturafacultad;
GRANT SELECT ON academico.vw_datos_personales_profesor TO decanaturafacultad;
GRANT SELECT ON academico.vw_buscador_cursos TO decanaturafacultad;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_asignatura_grupos TO decanaturafacultad;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_grupos_disponibles TO decanaturafacultad;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_grupos_disponibles2 TO decanaturafacultad;
GRANT EXECUTE ON PROCEDURE academico.sp_buscador_cursos TO decanaturafacultad;
GRANT EXECUTE ON PROCEDURE academico.sp_facultades_por_sede TO decanaturafacultad;
GRANT EXECUTE ON PROCEDURE academico.sp_programas_por_facultades TO decanaturafacultad;
GRANT EXECUTE ON PROCEDURE academico.sp_seleccionar_rol TO decanaturafacultad;
GRANT EXECUTE ON FUNCTION academico.obtenerSemestreActual TO decanaturafacultad;
GRANT EXECUTE ON FUNCTION academico.aprobacion TO decanaturafacultad;
GRANT EXECUTE ON FUNCTION academico.obligatorio TO decanaturafacultad;

-- Asignación de permisos a Secretaría Facultad
GRANT SELECT ON academico.persona TO secretariafacultad;
GRANT SELECT ON academico.vinculado TO secretariafacultad;
GRANT SELECT ON academico.responsable TO secretariafacultad;
GRANT SELECT ON academico.profesor TO secretariafacultad;
GRANT SELECT ON academico.residencia TO secretariafacultad;
GRANT SELECT ON academico.estudiante TO secretariafacultad;
GRANT SELECT ON academico.estudiante_has_responsable TO secretariafacultad;
GRANT SELECT ON academico.sede TO secretariafacultad;
GRANT SELECT ON academico.facultad TO secretariafacultad;
GRANT SELECT ON academico.departamento TO secretariafacultad;
GRANT SELECT ON academico.programa TO secretariafacultad;
GRANT SELECT ON academico.asignatura TO secretariafacultad;
GRANT SELECT ON academico.prerrequisito TO secretariafacultad;
GRANT SELECT ON academico.grupo TO secretariafacultad;
GRANT SELECT ON academico.grupo_info TO secretariafacultad;
GRANT SELECT ON academico.historia_academica TO secretariafacultad;
GRANT SELECT ON academico.cita_por_historia_academica TO secretariafacultad;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.inscripcion TO secretariafacultad;
GRANT SELECT ON academico.calificacion TO secretariafacultad;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.ceremonia_grado TO secretariafacultad;
GRANT SELECT, INSERT, UPDATE ON academico.solicitud_inscripcion_grado TO secretariafacultad;
GRANT SELECT, INSERT, UPDATE ON academico.malla TO secretariafacultad;
GRANT SELECT, INSERT, UPDATE ON academico.agrupacion_asignaturas TO secretariafacultad;
GRANT SELECT, INSERT, UPDATE ON academico.asignatura_asociada TO secretariafacultad;
GRANT SELECT, UPDATE ON academico.solicitud_sobrecupo TO secretariafacultad;
GRANT SELECT ON academico.vw_fac_pro_sed TO secretariafacultad;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_pro_asignatura TO secretariafacultad;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_asignatura_prereq TO secretariafacultad;
GRANT SELECT ON academico.vw_estudiantes_act TO secretariafacultad;
GRANT SELECT ON academico.vw_historia_academica TO secretariafacultad;
GRANT SELECT ON academico.vw_calificacion_grupo TO secretariafacultad;
GRANT SELECT ON academico.vw_calificacion_asig TO secretariafacultad;
GRANT SELECT ON academico.vw_cita_inscrip TO secretariafacultad;
GRANT SELECT, UPDATE ON academico.vw_docentes_act TO secretariafacultad;
GRANT SELECT ON academico.vw_estudiantes_pregrado TO secretariafacultad;
GRANT SELECT ON academico.vw_estudiantes_posgrado TO secretariafacultad;
GRANT SELECT ON academico.vw_estudiantes_doble TO secretariafacultad;
GRANT SELECT ON academico.vw_estudiantes_reserva TO secretariafacultad;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_ceremonia_grado TO secretariafacultad;
GRANT SELECT, INSERT, UPDATE ON academico.vw_solicitud_inscripcion_grado TO secretariafacultad;
GRANT SELECT ON academico.vw_datos_personales_estudiante TO secretariafacultad;
GRANT SELECT ON academico.vw_datos_personales_profesor TO secretariafacultad;
GRANT SELECT ON academico.vw_buscador_cursos TO secretariafacultad;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_asignatura_grupos TO secretariafacultad;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_grupos_disponibles TO secretariafacultad;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_grupos_disponibles2 TO secretariafacultad;
GRANT EXECUTE ON PROCEDURE academico.sp_buscador_cursos TO secretariafacultad;
GRANT EXECUTE ON PROCEDURE academico.sp_facultades_por_sede TO secretariafacultad;
GRANT EXECUTE ON PROCEDURE academico.sp_programas_por_facultades TO secretariafacultad;
GRANT EXECUTE ON PROCEDURE academico.sp_traslado_programa TO secretariafacultad;
GRANT EXECUTE ON PROCEDURE academico.sp_seleccionar_rol TO secretariafacultad;
GRANT EXECUTE ON FUNCTION academico.obtenerSemestreActual TO secretariafacultad;
GRANT EXECUTE ON FUNCTION academico.aprobacion TO secretariafacultad;
GRANT EXECUTE ON FUNCTION academico.obligatorio TO secretariafacultad;

-- Asignación de permisos a Profesor
GRANT SELECT ON academico.profesor TO profesor;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.residencia TO profesor;
GRANT SELECT ON academico.sede TO profesor;
GRANT SELECT ON academico.facultad TO profesor;
GRANT SELECT ON academico.departamento TO profesor;
GRANT SELECT ON academico.programa TO profesor;
GRANT SELECT ON academico.asignatura TO profesor;
GRANT SELECT ON academico.prerrequisito TO profesor;
GRANT SELECT ON academico.grupo TO profesor;
GRANT SELECT ON academico.grupo_info TO profesor;
GRANT SELECT ON academico.calificacion TO profesor;
GRANT SELECT ON academico.ceremonia_grado TO profesor;
GRANT SELECT ON academico.malla TO profesor;
GRANT SELECT ON academico.agrupacion_asignaturas TO profesor;
GRANT SELECT ON academico.asignatura_asociada TO profesor;
GRANT SELECT ON academico.vw_fac_pro_sed TO profesor;
GRANT SELECT ON academico.vw_pro_asignatura TO profesor;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_calificacion_grupo TO profesor;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.vw_calificacion_asig TO profesor;
GRANT SELECT ON academico.vw_ceremonia_grado TO profesor;
GRANT SELECT, UPDATE ON academico.vw_datos_personales_profesor TO profesor;
GRANT SELECT ON academico.vw_buscador_cursos TO profesor;
GRANT SELECT ON academico.vw_asignatura_grupos TO profesor;
GRANT SELECT ON academico.vw_grupos_disponibles TO profesor;
GRANT SELECT ON academico.vw_grupos_disponibles2 TO profesor;
GRANT EXECUTE ON PROCEDURE academico.sp_buscador_cursos TO profesor;
GRANT EXECUTE ON PROCEDURE academico.sp_facultades_por_sede TO profesor;
GRANT EXECUTE ON PROCEDURE academico.sp_programas_por_facultades TO profesor;
GRANT EXECUTE ON PROCEDURE academico.sp_seleccionar_rol TO profesor;
GRANT EXECUTE ON FUNCTION academico.obtenerSemestreActual TO profesor;
GRANT EXECUTE ON FUNCTION academico.aprobacion TO profesor;
GRANT EXECUTE ON FUNCTION academico.obligatorio TO profesor;

-- Asignación de permisos a Estudiante
GRANT SELECT, INSERT, UPDATE ON academico.responsable TO estudiante;
GRANT SELECT, INSERT, UPDATE ON academico.residencia TO estudiante;
GRANT SELECT, UPDATE ON academico.estudiante TO estudiante;
GRANT SELECT, INSERT, UPDATE, DELETE ON academico.estudiante_has_responsable TO estudiante;
GRANT SELECT ON academico.facultad TO estudiante;
GRANT SELECT ON academico.departamento TO estudiante;
GRANT SELECT ON academico.programa TO estudiante;
GRANT SELECT ON academico.asignatura TO estudiante;
GRANT SELECT ON academico.prerrequisito TO estudiante;
GRANT SELECT ON academico.grupo TO estudiante;
GRANT SELECT ON academico.grupo_info TO estudiante;
GRANT SELECT ON academico.historia_academica TO estudiante;
GRANT SELECT ON academico.cita_por_historia_academica TO estudiante;
GRANT SELECT ON academico.inscripcion TO estudiante;
GRANT SELECT ON academico.calificacion TO estudiante;
GRANT SELECT ON academico.ceremonia_grado TO estudiante;
GRANT SELECT,INSERT ON academico.solicitud_inscripcion_grado TO estudiante;
GRANT SELECT ON academico.malla TO estudiante;
GRANT SELECT ON academico.agrupacion_asignaturas TO estudiante;
GRANT SELECT ON academico.asignatura_asociada TO estudiante;
GRANT SELECT, INSERT ON academico.solicitud_sobrecupo TO estudiante;
GRANT SELECT ON academico.vw_fac_pro_sed TO estudiante;
GRANT SELECT ON academico.vw_pro_asignatura TO estudiante;
GRANT SELECT ON academico.vw_asignatura_prereq TO estudiante;
GRANT SELECT ON academico.vw_historia_academica TO estudiante;
GRANT SELECT ON academico.vw_calificacion_grupo TO estudiante;
GRANT SELECT ON academico.vw_calificacion_asig TO estudiante;
GRANT SELECT ON academico.vw_cita_inscrip TO estudiante;
GRANT SELECT ON academico.vw_estudiantes_reserva TO estudiante;
GRANT SELECT ON academico.vw_ceremonia_grado TO estudiante;
GRANT SELECT, INSERT ON academico.vw_solicitud_inscripcion_grado TO estudiante;
GRANT SELECT, UPDATE ON academico.vw_datos_personales_estudiante TO estudiante;
GRANT SELECT ON academico.vw_buscador_cursos TO estudiante;
GRANT SELECT ON academico.vw_asignatura_grupos TO estudiante;
GRANT SELECT ON academico.vw_grupos_disponibles TO estudiante;
GRANT SELECT ON academico.vw_grupos_disponibles2 TO estudiante;
GRANT EXECUTE ON PROCEDURE academico.sp_actualizar_PAPA TO estudiante;
GRANT EXECUTE ON PROCEDURE academico.sp_actualizar_PAPPI TO estudiante;
GRANT EXECUTE ON PROCEDURE academico.sp_programas_est TO estudiante;
GRANT EXECUTE ON PROCEDURE academico.sp_asignaturas_historia TO estudiante;
GRANT EXECUTE ON PROCEDURE academico.sp_info_personal TO estudiante;
GRANT EXECUTE ON PROCEDURE academico.sp_est_actualizar_datos TO estudiante;
GRANT EXECUTE ON PROCEDURE academico.sp_resumen_creditos TO estudiante;
GRANT EXECUTE ON PROCEDURE academico.sp_inscripcion_prerrequisito TO estudiante;
GRANT EXECUTE ON PROCEDURE academico.sp_grupos_por_asignatura TO estudiante;
GRANT EXECUTE ON PROCEDURE academico.sp_inscripcion_le TO estudiante;
GRANT EXECUTE ON PROCEDURE academico.sp_inscripcion_sobrecupo TO estudiante;
GRANT EXECUTE ON PROCEDURE academico.sp_grupos_sobrecupo TO estudiante;
GRANT EXECUTE ON PROCEDURE academico.sp_cupo_creditos TO estudiante;
GRANT EXECUTE ON PROCEDURE academico.sp_horario_est TO estudiante;
GRANT EXECUTE ON PROCEDURE academico.sp_buscador_cursos TO estudiante;
GRANT EXECUTE ON PROCEDURE academico.sp_facultades_por_sede TO estudiante;
GRANT EXECUTE ON PROCEDURE academico.sp_programas_por_facultades TO estudiante;
GRANT EXECUTE ON PROCEDURE academico.sp_seleccionar_rol TO estudiante;
GRANT EXECUTE ON FUNCTION academico.obtenerSemestreActual TO estudiante;
GRANT EXECUTE ON FUNCTION academico.aprobacion TO estudiante;
GRANT EXECUTE ON FUNCTION academico.obligatorio TO estudiante;
GRANT EXECUTE ON FUNCTION academico.getPAPA TO estudiante;
GRANT EXECUTE ON FUNCTION academico.getPAPPI TO estudiante;
GRANT EXECUTE ON FUNCTION academico.getAvance TO estudiante;
GRANT EXECUTE ON FUNCTION academico.getTotalCreditosCancelados TO estudiante;
GRANT EXECUTE ON FUNCTION academico.getCreditosCanceladosActual TO estudiante;
GRANT EXECUTE ON FUNCTION academico.getCreditosExcedentes TO estudiante;

-- Limpieza de usuarios antes de comenzar
DROP USER IF EXISTS 'mario'@'localhost';
DROP USER IF EXISTS 'pedro'@'localhost';
DROP USER IF EXISTS 'jose'@'localhost';
DROP USER IF EXISTS 'camilo'@'localhost';
DROP USER IF EXISTS 'pepe'@'localhost';
DROP USER IF EXISTS 'juan'@'localhost';
DROP USER IF EXISTS 'esteban'@'localhost';
DROP USER IF EXISTS 'camila'@'localhost';
DROP USER IF EXISTS 'laura'@'localhost';
DROP USER IF EXISTS 'facultadingenieria'@'localhost';
DROP USER IF EXISTS 'david'@'localhost';

-- Creación de 11 usuarios distintos con sus distintas claves de acceso
CREATE USER 'mario'@'localhost' IDENTIFIED BY 'vs12345';
CREATE USER 'pedro'@'localhost' IDENTIFIED BY 'drym12345';
CREATE USER 'jose'@'localhost' IDENTIFIED BY 'p12345';
CREATE USER 'camilo'@'localhost' IDENTIFIED BY 'e12345';
CREATE USER 'pepe'@'localhost' IDENTIFIED BY 'sg12345';
CREATE USER 'juan'@'localhost' IDENTIFIED BY 'dcpr12345';
CREATE USER 'esteban'@'localhost' IDENTIFIED BY 'dcpo12345';
CREATE USER 'camila'@'localhost' IDENTIFIED BY 'dia12345';
CREATE USER 'laura'@'localhost' IDENTIFIED BY 'dspn12345';
CREATE USER 'facultadingenieria'@'localhost' IDENTIFIED BY 'df12345';
CREATE USER 'david'@'localhost' IDENTIFIED BY 'sf12345';
create user 'currutiab'@'localhost' identified by 'JFDhtr78';


-- Asignación de permisos a los usuarios
GRANT vicerrectoriasede TO 'mario'@'localhost';
GRANT divisionderegistroymatricula TO 'pedro'@'localhost';
GRANT profesor TO 'jose'@'localhost';
GRANT estudiante TO 'camilo'@'localhost';
GRANT secretariageneral TO 'pepe'@'localhost';
GRANT direccioncurricularpregrado TO 'juan'@'localhost';
GRANT direccioncurricularposgrado TO 'esteban'@'localhost';
GRANT direccioninformacionacademica TO 'camila'@'localhost';
GRANT direccionsedespresencianal TO 'laura'@'localhost';
GRANT decanaturafacultad TO 'facultadingenieria'@'localhost';
GRANT secretariafacultad TO 'david'@'localhost';
GRANT estudiante TO 'currutiab'@'localhost';



