/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package loginsia;

import com.academico.login.conexion.SQLConnection;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import static loginsia.SIA.Ventana;

/**
 *
 * @author HUERTAS
 */
public class Buscador extends javax.swing.JInternalFrame {

    private String usuario;
    private String contrasena;
    private DefaultTableModel cursos;
    SQLConnection cc = new SQLConnection();
    private Connection conexion;
    private ResultSet rs;
    private String programa;
    private String tipologia;
    private Integer creditos;
    private String dias;
    private String asignatura;
    
    public Buscador(String usuario, String contrasena, String programa, String tipologia, Integer creditos, String dias,String asignatura) {
        initComponents();
        this.usuario = usuario;
        this.contrasena = contrasena;
        this.programa = programa;
        this.tipologia = tipologia;
        this.creditos= creditos;
        this.dias = dias;
        this.asignatura = asignatura;
    
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui1 = (BasicInternalFrameUI) this.getUI();
        ui1.setNorthPane(null);
        this.conexion = cc.conexion(usuario,contrasena);
        Buscador.setFillsViewportHeight(true);
        
        
        this.cursos = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int filas,int columnas){
                return false;
            }
        };
        cursos.addColumn("Código");
        cursos.addColumn("Asignatura");
        cursos.addColumn("Créditos");
        cursos.addColumn("Tipología");
        Buscador.setModel(cursos);
        
        
        try {
            String sql = "{CALL sp_buscador_cursos(?,?,?,?,?)}";
            CallableStatement callableStatement = conexion.prepareCall(sql);
            
            
            // Establecer los parámetros de entrada del procedimiento  
            if (programa != null) {
                callableStatement.setString(1, programa);
                System.out.println("1");
            } else {
                callableStatement.setObject(1, programa);   
            }
            
            if (tipologia != null) {
                callableStatement.setString(2, tipologia);
            } else {
                callableStatement.setObject(2, tipologia); 
                System.out.println("2");
            }
            
            if (creditos != null) {
                callableStatement.setInt(3, creditos);
            } else {
                callableStatement.setObject(3, creditos);   
                System.out.println("3");
            }
            
            if (asignatura != null) {
                callableStatement.setString(4, asignatura);
            } else {
                callableStatement.setObject(4, asignatura);  
            }
            
            callableStatement.setString(5, dias);
            
            
            

            // Recorrer los resultados
            ResultSet resultSet = callableStatement.executeQuery();
            String[] datos = new String[4];
            System.out.println("llega A");
            while(resultSet.next()){
                System.out.println("llega B");
                datos[0] = resultSet.getString("codigo");
                datos[1] = resultSet.getString("asignatura");
                datos[2] = String.valueOf(resultSet.getInt("creditos"));
                datos[3] = resultSet.getString("tipologia");
                cursos.addRow(datos);
            }
           
        } catch (SQLException ex) {
            Logger.getLogger(Historia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Buscador = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Buscador de cursos");

        Buscador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Buscador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscadorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Buscador);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1078, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscadorMouseClicked
        if (evt.getClickCount() == 2){
            String asignatura = String.valueOf(Buscador.getValueAt(Buscador.getSelectedRow(), 0));
            GruAsigBuscador asig = new GruAsigBuscador(this.usuario,this.contrasena,asignatura,this.programa,this.tipologia,this.creditos,this.dias,this.asignatura);
            Ventana.removeAll();
            Ventana.updateUI();
            Ventana.add(asig);
            asig.setVisible(true);
        }
    }//GEN-LAST:event_BuscadorMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Buscador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
