/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package loginsia;

import com.academico.login.conexion.SQLConnection;
import com.mysql.cj.util.StringUtils;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.lang.model.util.Types;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import static loginsia.SIA.Ventana;

/**
 *
 * @author HUERTAS
 */
public class FiltrarCursos extends javax.swing.JInternalFrame {
    
    SQLConnection cc = new SQLConnection();
    private Connection conexion;
    private ResultSet rs;
    private String usuario;
    private String contrasena;
    private String dias = "";
    /**
     * Creates new form FiltrarCursos
     */
    public FiltrarCursos(String usuario, String contrasena) {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui1 = (BasicInternalFrameUI) this.getUI();
        ui1.setNorthPane(null);
        this.usuario = usuario;
        this.contrasena = contrasena;
        this.conexion = cc.conexion(this.usuario,this.contrasena);
        
        SedeBox.setEnabled(false);
        TipoBox.setEnabled(false);
        CreText.setEnabled(false);
        NomText.setEnabled(false);
        BuscadorButton.setEnabled(false);
        ProgramaBox.setEnabled(false);
        FacultadBox.setEnabled(false);
        ProgramaBox.setSelectedItem(null);
        SedeBox.setSelectedItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FacultadBox = new javax.swing.JComboBox<>();
        NivelBox = new javax.swing.JComboBox<>();
        SedeBox = new javax.swing.JComboBox<>();
        ProgramaBox = new javax.swing.JComboBox<>();
        TipoBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NomText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CreText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Bmar = new javax.swing.JRadioButton();
        Blun = new javax.swing.JRadioButton();
        Bsab = new javax.swing.JRadioButton();
        Bmie = new javax.swing.JRadioButton();
        Bjue = new javax.swing.JRadioButton();
        Bvie = new javax.swing.JRadioButton();
        Bdom = new javax.swing.JRadioButton();
        BuscadorButton = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Selecciona qué deseas consultar:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setText("Buscador de cursos");

        FacultadBox.setSelectedItem(null);
        FacultadBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                FacultadBoxItemStateChanged(evt);
            }
        });
        FacultadBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacultadBoxActionPerformed(evt);
            }
        });

        NivelBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pregrado", "Postgrados y másteres", "Doctorado" }));
        NivelBox.setSelectedItem(null);
        NivelBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NivelBoxItemStateChanged(evt);
            }
        });
        NivelBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NivelBoxActionPerformed(evt);
            }
        });

        SedeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1125 SEDE AMAZONIA", "1101 SEDE BOGOTÁ", "1126 SEDE CARIBE", "9933 SEDE DE LA PAZ", "1103 SEDE MANIZALES", "1102 SEDE MEDELLÍN", "1124 SEDE ORINOQUIA", "1104 SEDE PALMIRA", "9920 SEDE TUMACO" }));
        SedeBox.setSelectedItem(null);
        SedeBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SedeBoxItemStateChanged(evt);
            }
        });
        SedeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SedeBoxActionPerformed(evt);
            }
        });

        ProgramaBox.setSelectedItem(null);
        ProgramaBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ProgramaBoxItemStateChanged(evt);
            }
        });
        ProgramaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProgramaBoxActionPerformed(evt);
            }
        });

        TipoBox.setSelectedItem(null);
        TipoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoBoxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setText("Sede:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setText("*Nivel de estudio:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setText("*Plan de estudios:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel6.setText("*Facultad:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel7.setText("Tipología:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel8.setText("Días:");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel9.setText("Número de créditos:");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel10.setText("Nombre:");

        Bmar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Bmar.setText("Martes");
        Bmar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BmarStateChanged(evt);
            }
        });
        Bmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmarActionPerformed(evt);
            }
        });

        Blun.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Blun.setText("Lunes");
        Blun.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BlunStateChanged(evt);
            }
        });
        Blun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlunActionPerformed(evt);
            }
        });

        Bsab.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Bsab.setText("Sábado");
        Bsab.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BsabStateChanged(evt);
            }
        });
        Bsab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsabActionPerformed(evt);
            }
        });

        Bmie.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Bmie.setText("Miércoles");
        Bmie.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BmieStateChanged(evt);
            }
        });
        Bmie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmieActionPerformed(evt);
            }
        });

        Bjue.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Bjue.setText("Jueves");
        Bjue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BjueStateChanged(evt);
            }
        });
        Bjue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BjueActionPerformed(evt);
            }
        });

        Bvie.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Bvie.setText("Viernes");
        Bvie.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BvieStateChanged(evt);
            }
        });
        Bvie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BvieActionPerformed(evt);
            }
        });

        Bdom.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Bdom.setText("Domingo");
        Bdom.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BdomStateChanged(evt);
            }
        });
        Bdom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdomActionPerformed(evt);
            }
        });

        BuscadorButton.setBackground(new java.awt.Color(96, 25, 25));
        BuscadorButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BuscadorButton.setForeground(new java.awt.Color(255, 255, 255));
        BuscadorButton.setText("Buscar");
        BuscadorButton.setToolTipText("");
        BuscadorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscadorButtonMouseClicked(evt);
            }
        });
        BuscadorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscadorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(750, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NomText, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SedeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FacultadBox, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProgramaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NivelBox, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CreText, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TipoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BuscadorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(Blun)
                                .addGap(18, 18, 18)
                                .addComponent(Bmar)
                                .addGap(18, 18, 18)
                                .addComponent(Bmie)
                                .addGap(18, 18, 18)
                                .addComponent(Bjue)))
                        .addGap(18, 18, 18)
                        .addComponent(Bvie)
                        .addGap(18, 18, 18)
                        .addComponent(Bsab)
                        .addGap(18, 18, 18)
                        .addComponent(Bdom)))
                .addGap(240, 240, 240))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NivelBox, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SedeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(FacultadBox, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProgramaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Bmar)
                    .addComponent(Blun)
                    .addComponent(Bsab)
                    .addComponent(Bmie)
                    .addComponent(Bjue)
                    .addComponent(Bvie)
                    .addComponent(Bdom))
                .addGap(31, 31, 31)
                .addComponent(BuscadorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NivelBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NivelBoxActionPerformed
        
    }//GEN-LAST:event_NivelBoxActionPerformed

    private void SedeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SedeBoxActionPerformed

    }//GEN-LAST:event_SedeBoxActionPerformed

    private void FacultadBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacultadBoxActionPerformed
        
        
    }//GEN-LAST:event_FacultadBoxActionPerformed

    private void BmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmarActionPerformed
        if (Bmar.isSelected()) {
            if (this.dias.equals("")) {
                this.dias = this.dias + "martes";
            } else {
                this.dias = this.dias + ",martes";
            }
        } else {
            this.dias = EliminarDia(this.dias,"martes");
        }
    }//GEN-LAST:event_BmarActionPerformed

    private void BlunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlunActionPerformed
        if (Blun.isSelected()) {
            if (this.dias.equals("")) {
                this.dias = this.dias + "lunes";
            } else {
                this.dias = this.dias + ",lunes";
            }
        } else {
            this.dias = EliminarDia(this.dias,"lunes");
        }
    }//GEN-LAST:event_BlunActionPerformed

    private void BsabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsabActionPerformed
        if (Bsab.isSelected()) {
            if (this.dias.equals("")) {
                this.dias = this.dias + "sábado";
            } else {
                this.dias = this.dias + ",sábado";
            }
        } else {
            this.dias = EliminarDia(this.dias,"sábado");
        }
    }//GEN-LAST:event_BsabActionPerformed

    private void BmieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmieActionPerformed
        if (Bmie.isSelected()) {
            if (this.dias.equals("")) {
                this.dias = this.dias + "miércoles";
            } else {
                this.dias = this.dias + ",miércoles";
            }
        } else {
            this.dias = EliminarDia(this.dias,"miércoles");
        }
    }//GEN-LAST:event_BmieActionPerformed

    private void BjueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BjueActionPerformed
        if (Bjue.isSelected()) {
            if (this.dias.equals("")) {
                this.dias = this.dias + "jueves";
            } else {
                this.dias = this.dias + ",jueves";
            }
        } else {
            this.dias = EliminarDia(this.dias,"jueves");
        }
    }//GEN-LAST:event_BjueActionPerformed

    private void BvieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BvieActionPerformed
        if (Bvie.isSelected()) {
            if (this.dias.equals("")) {
                this.dias = this.dias + "viernes";
            } else {
                this.dias = this.dias + ",viernes";
            }
        } else {
            this.dias = EliminarDia(this.dias,"viernes");
        }
    }//GEN-LAST:event_BvieActionPerformed

    private void BdomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdomActionPerformed
        if (Bdom.isSelected()) {
            if (this.dias.equals("")) {
                this.dias = this.dias + "domingo";
            } else {
                this.dias = this.dias + ",domingo";
            }
        } else {
            this.dias = EliminarDia(this.dias,"domingo");
        }
    }//GEN-LAST:event_BdomActionPerformed

    private void BlunStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BlunStateChanged
        
    }//GEN-LAST:event_BlunStateChanged

    private void BmarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BmarStateChanged
        
    }//GEN-LAST:event_BmarStateChanged

    private void BmieStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BmieStateChanged
        
    }//GEN-LAST:event_BmieStateChanged

    private void BjueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BjueStateChanged
        
    }//GEN-LAST:event_BjueStateChanged

    private void BvieStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BvieStateChanged
        
    }//GEN-LAST:event_BvieStateChanged

    private void BsabStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BsabStateChanged
        
    }//GEN-LAST:event_BsabStateChanged

    private void BdomStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BdomStateChanged
        
    }//GEN-LAST:event_BdomStateChanged

    private void BuscadorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscadorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscadorButtonActionPerformed

    private void BuscadorButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscadorButtonMouseClicked

        String programa = null;
        String tipologia = null;
        Integer creditos = null;
        String asignatura = null;
        
        if (ProgramaBox.getSelectedItem() != null) {
            programa = String.format("%."+ 4 +"s",ProgramaBox.getSelectedItem());
            System.out.println(programa);
        }
        if (TipoBox.getSelectedItem() != null) {
            tipologia = TipoBox.getSelectedItem().toString();
            if (tipologia.equals("FUND. OPTATIVA")){
                tipologia = "FUNDAMENTACIÓN  OPTATIVA";
            } else if (tipologia.equals("FUND. OBLIGATORIA")) {
                tipologia = "FUNDAMENTACIÓN  OBLIGATORIA";
            }
        }
        if (CreText.getText().length() != 0) {
            creditos = Integer.valueOf(CreText.getText());
        }
        if (NomText.getText().length() != 0) {
            asignatura = NomText.getText();
        }
        System.out.println(dias);
        System.out.println(programa);
        System.out.println(tipologia);
        System.out.println(asignatura);
        Buscador buscador_cursos = new Buscador(this.usuario,this.contrasena,programa,tipologia,creditos,dias,asignatura);
        Ventana.removeAll();
        Ventana.updateUI();
        Ventana.add(buscador_cursos);
        buscador_cursos.setVisible(true);
    }//GEN-LAST:event_BuscadorButtonMouseClicked

    private void ProgramaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProgramaBoxActionPerformed
        if (ProgramaBox.getSelectedItem() != null) {
            TipoBox.setEnabled(true);
            
        }
    }//GEN-LAST:event_ProgramaBoxActionPerformed

    private void NivelBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NivelBoxItemStateChanged
        if (NivelBox.getSelectedItem() != null){
            SedeBox.setEnabled(true);
            SedeBox.setSelectedItem(null);
            FacultadBox.setEnabled(true);    
            FacultadBox.setSelectedItem(null);
            ProgramaBox.setEnabled(false);
            ProgramaBox.setSelectedItem(null);
            TipoBox.setEnabled(false);
            TipoBox.setSelectedItem(null);
            CreText.setEnabled(false);
            NomText.setEnabled(false);
            cargarFacultad();
        }
    }//GEN-LAST:event_NivelBoxItemStateChanged

    private void SedeBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SedeBoxItemStateChanged
        if(SedeBox.getSelectedItem() != null){
            ProgramaBox.setEnabled(false);
            ProgramaBox.removeAllItems();
            FacultadBox.setEnabled(true);    
            cargarFacultad();
            FacultadBox.setSelectedItem(null);
            BuscadorButton.setEnabled(false);
        }
    }//GEN-LAST:event_SedeBoxItemStateChanged

    private void FacultadBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_FacultadBoxItemStateChanged
        if(FacultadBox.getSelectedItem() != null) {
            ProgramaBox.setEnabled(true);
            cargarProgramas(); 
            ProgramaBox.setSelectedItem(null);
            TipoBox.setEnabled(false);
            CreText.setEnabled(false);
            NomText.setEnabled(false);
            BuscadorButton.setEnabled(false);
        }
    }//GEN-LAST:event_FacultadBoxItemStateChanged

    private void ProgramaBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ProgramaBoxItemStateChanged
        if(ProgramaBox.getSelectedItem() != null){
            TipoBox.setEnabled(true);
            cargarTipologia(NivelBox.getSelectedItem().toString());
            TipoBox.setSelectedItem(null);
            BuscadorButton.setEnabled(true);
            CreText.setEnabled(true);
            NomText.setEnabled(true);
        }
    }//GEN-LAST:event_ProgramaBoxItemStateChanged

    private void TipoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoBoxActionPerformed

    private void cargarFacultad(){
        try {
            CallableStatement sp1 = conexion.prepareCall("{CALL sp_facultades_buscador(?,?)}");
            if (SedeBox.getSelectedItem() != null){
                sp1.setInt(1, Integer.parseInt(String.format("%."+ 4 +"s",SedeBox.getSelectedItem())));
            } else {
                sp1.setObject(1,null);
            }
            
            sp1.setString(2, (String) NivelBox.getSelectedItem());
            ResultSet rs1 = sp1.executeQuery();
            ArrayList<String> facultades = new ArrayList<>();
            facultades.add(null);
            FacultadBox.removeAllItems();
            while(rs1.next()){
                facultades.add(rs1.getString("facultad"));
            }
            for (int i = 0;i < facultades.size(); i++){
                FacultadBox.addItem(facultades.get(i));
        }
        
    }   catch (SQLException ex) {
            Logger.getLogger(FiltrarCursos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void cargarProgramas(){
        try {
            CallableStatement sp2 = conexion.prepareCall("{CALL sp_programas_por_facultades(?)}");
            sp2.setInt(1, Integer.parseInt(String.format("%."+ 4 +"s",FacultadBox.getSelectedItem())));
            ResultSet rs2 = sp2.executeQuery();
            ArrayList<String> programas = new ArrayList<>();
            programas.add(null);
            programas.add("2CLE Componente de libre elección");
            ProgramaBox.removeAllItems();
            while(rs2.next()){
                programas.add(rs2.getString("programa"));
            }
            for (int i = 0;i < programas.size(); i++){
                ProgramaBox.addItem(programas.get(i));
        }
        
    }   catch (SQLException ex) {
            Logger.getLogger(FiltrarCursos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void cargarTipologia(String s) {
        switch (s) {
            case "Pregrado" -> {
                TipoBox.addItem(null);
                TipoBox.addItem("TODAS MENOS LIBRE ELECCIÓN");
                TipoBox.addItem("DISCIPLINAR  OPTATIVA");
                TipoBox.addItem("FUND. OBLIGATORIA");
                TipoBox.addItem("FUND. OPTATIVA");
                TipoBox.addItem("TRABAJO DE GRADO");
                TipoBox.addItem("DISCIPLINAR  OBLIGATORIA");
                TipoBox.addItem("NIVELACION");
                TipoBox.addItem("LIBRE ELECCIÓN");
            }
            case "Postgrados y másteres" -> {
                TipoBox.addItem(null);
                TipoBox.addItem("TODAS MENOS ELEGIBLES");
                TipoBox.addItem("TESIS");
                TipoBox.addItem("OBLIGATORIA");
                TipoBox.addItem("ELECTIVA DE PREGRADO");
                TipoBox.addItem("ACTIVIDADES ACADÉMICAS");
                TipoBox.addItem("NIVELACION");
                TipoBox.addItem("ELEGIBLES");
            }
            case "Doctorado" -> {
                TipoBox.addItem(null);
                TipoBox.addItem("TODAS MENOS ELEGIBLES");
                TipoBox.addItem("ELECTIVA DEL PLAN");
                TipoBox.addItem("OBLIGATORIAS");
                TipoBox.addItem("CURSOS DE CONTEXTO");
                TipoBox.addItem("TESIS-TRAB. FINAL");
                TipoBox.addItem("ACTIVIDADES ACADÉMICAS");
                TipoBox.addItem("ELECTIVA DE PREGRADO");
                TipoBox.addItem("ELEGIBLES");
            }
        }
    }
    
    public static String EliminarDia(String texto, String select) {

        String[] dias = texto.split(",");
        
        StringBuilder nuevaCadena = new StringBuilder();
        
        for (String dia : dias) {
            if (!dia.equals(select)) {
                nuevaCadena.append(dia).append(",");
            }
        }
        
        // Eliminar la última coma si existe
        if (nuevaCadena.length() > 0 && nuevaCadena.charAt(nuevaCadena.length() - 1) == ',') {
            nuevaCadena.deleteCharAt(nuevaCadena.length() - 1);
        }
        
        return String.valueOf(nuevaCadena);
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Bdom;
    private javax.swing.JRadioButton Bjue;
    private javax.swing.JRadioButton Blun;
    private javax.swing.JRadioButton Bmar;
    private javax.swing.JRadioButton Bmie;
    private javax.swing.JRadioButton Bsab;
    private javax.swing.JButton BuscadorButton;
    private javax.swing.JRadioButton Bvie;
    private javax.swing.JTextField CreText;
    private javax.swing.JComboBox<String> FacultadBox;
    private javax.swing.JComboBox<String> NivelBox;
    private javax.swing.JTextField NomText;
    private javax.swing.JComboBox<String> ProgramaBox;
    private javax.swing.JComboBox<String> SedeBox;
    private javax.swing.JComboBox<String> TipoBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
