/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package loginsia;

import com.academico.login.conexion.SQLConnection;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import static loginsia.SIA.Ventana;

/**
 *
 * @author HUERTAS
 */
public class GruposAsigSobreCupo extends javax.swing.JInternalFrame {

    private String asi_codigo;
    private String usuario;
    private String contrasena;
    private DefaultTableModel asig;
    SQLConnection cc = new SQLConnection();
    private Connection conexion;
    private String programa;

    /**
     * Creates new form GruposAsig
     */
    public GruposAsigSobreCupo(String usuario,String contrasena,String asi_codigo,String programa) {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui1 = (BasicInternalFrameUI) this.getUI();
        ui1.setNorthPane(null);
        this.conexion = cc.conexion(usuario,contrasena);
        
        this.asi_codigo = asi_codigo;
        this.usuario = usuario;
        this.contrasena = contrasena;
        this.programa = programa;
        
        this.asig = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int filas,int columnas){
                return columnas == 2;
            }
        };
        
        asig.addColumn("Asignatura");
        asig.addColumn("Grupo");
        asig.addColumn("Solicitar Sobrecupo");

        asignaturas.setModel(asig);
        addCheckBox(2,asignaturas);
        asignaturas.setFillsViewportHeight(true);
            try {
            String sql = "{CALL sp_grupos_por_asignatura_sc(?,?,?)}";
            CallableStatement callableStatement = conexion.prepareCall(sql);

            // Establecer los parámetros de entrada del procedimiento  
            callableStatement.setString(1, this.usuario);
            callableStatement.setString(2, this.programa);
            callableStatement.setString(3, this.asi_codigo);

            // Ejecutar el procedimiento almacenado
            ResultSet rs = callableStatement.executeQuery();

            // Recorrer los resultados}
            if(rs.next()){
                String[] datos = new String[2];
                do {
                    datos[0] = rs.getString("asignatura");
                    datos[1] = String.valueOf(rs.getInt("grupo"));
                    asig.addRow(datos);
                } while(rs.next());
            }
            
                
        } catch (SQLException ex) {
            Logger.getLogger(Historia.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }
    
    private void addCheckBox(int column,JTable table){
        TableColumn tc = table.getColumnModel().getColumn(column);
        tc.setCellEditor(table.getDefaultEditor(Boolean.class));
        tc.setCellRenderer(table.getDefaultRenderer(Boolean.class));
    }
    
    private boolean isSelected(int row,int column,JTable table){
        Boolean s = Boolean.valueOf(String.valueOf(table.getValueAt(row, column)));
        return s == true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        asignaturas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        prioridad = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(96, 25, 25));
        jButton1.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Volver");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        titleLabel.setText("Solicitud de sobrecupo");

        asignaturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(asignaturas);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Si no selecciona ningún grupo, el sobrecupo será  solicitado para cualquiera de ellos.");

        prioridad.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        prioridad.setText("Prioridad de inscripción");

        jButton2.setBackground(new java.awt.Color(96, 25, 25));
        jButton2.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Solicitar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1021, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(16, 16, 16))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(471, 471, 471)
                        .addComponent(prioridad))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(prioridad)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Cita0 inscripcion = new Cita0(this.usuario,this.contrasena,this.programa);
        Ventana.removeAll();
        Ventana.updateUI();
        Ventana.add(inscripcion);
        inscripcion.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        try {
            this.conexion = cc.conexion(usuario,contrasena);
            CallableStatement sp1 = conexion.prepareCall("{CALL sp_solicitar_sobrecupo(?,?,?,?,?)}");
            sp1.setString(1, usuario);
            sp1.setString(2, programa);
            sp1.setString(3, asi_codigo);  
            sp1.setBoolean(5, prioridad.isSelected());
            int contador = 0;
            for(int i = 0; i < asignaturas.getRowCount(); i++){
                if(isSelected(i,2,asignaturas)){
                    contador++;
                }
            }
            if (contador > 1) {
                JOptionPane.showMessageDialog(null,"No puede solicitar el sobrecupo con prioridad a más de un grupo");
            } else if (contador == 0){
                sp1.setObject(4,null);
                ResultSet rs = sp1.executeQuery();
            }else {
                sp1.setInt(4, Integer.parseInt(String.valueOf(asignaturas.getValueAt(asignaturas.getSelectedRow(), 1))));
                ResultSet rs = sp1.executeQuery();
            }
        } catch (SQLException ex) {
            Logger.getLogger(GruposAsigSobreCupo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex);
            Cita0 inscripcion = new Cita0(this.usuario,this.contrasena,this.programa);
            Ventana.removeAll();
            Ventana.updateUI();
            Ventana.add(inscripcion);
            inscripcion.setVisible(true);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable asignaturas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton prioridad;
    public javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
