/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginsia;

import javax.swing.JOptionPane;
import java.sql.*;
import com.academico.login.conexion.SQLConnection;
import java.awt.HeadlessException;

/**
 *
 * @author HUERTAS
 */
public class RolSelect extends javax.swing.JFrame {

    
    int xMouse, yMouse;
    SQLConnection cc = new SQLConnection();
    private String usuario;
    private String contrasena;
    private Connection conexion;
    
    
    
     
public RolSelect(String usuario,String contrasena) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.usuario = usuario;
        this.contrasena = contrasena;
        this.conexion = cc.conexion(usuario,contrasena);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        Encabezado = new javax.swing.JPanel();
        Fondo = new javax.swing.JPanel();
        Form = new loginsia.PanelRound();
        Usuario = new javax.swing.JLabel();
        B_IniciarSesion = new javax.swing.JButton();
        B_Salir = new javax.swing.JButton();
        Selector = new javax.swing.JComboBox<>();
        SIA = new javax.swing.JLabel();
        LogoUNAL = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        Encabezado.setBackground(new java.awt.Color(217, 217, 217));
        Encabezado.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                EncabezadoMouseDragged(evt);
            }
        });
        Encabezado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EncabezadoMousePressed(evt);
            }
        });
        Encabezado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EncabezadoKeyPressed(evt);
            }
        });

        Fondo.setBackground(new java.awt.Color(96, 25, 25));

        Form.setBackground(new java.awt.Color(255, 255, 255));
        Form.setRoundBottomLeft(50);
        Form.setRoundBottomRight(50);
        Form.setRoundTopLeft(50);
        Form.setRoundTopRight(50);

        Usuario.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        Usuario.setText("Seleccionar rol");

        B_IniciarSesion.setBackground(new java.awt.Color(96, 25, 25));
        B_IniciarSesion.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        B_IniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        B_IniciarSesion.setText("Seleccionar");
        B_IniciarSesion.setBorder(null);
        B_IniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_IniciarSesionMouseClicked(evt);
            }
        });
        B_IniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_IniciarSesionActionPerformed(evt);
            }
        });

        B_Salir.setBackground(new java.awt.Color(96, 25, 25));
        B_Salir.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        B_Salir.setForeground(new java.awt.Color(255, 255, 255));
        B_Salir.setText("Volver");
        B_Salir.setActionCommand("");
        B_Salir.setBorder(null);
        B_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_SalirMouseClicked(evt);
            }
        });
        B_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_SalirActionPerformed(evt);
            }
        });

        Selector.setBackground(new java.awt.Color(217, 217, 217));
        Selector.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Selector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Profesor", "Vicerrectoria sede", "Secretaria general", "Direccion curricular pregrado", "Direccion curricular posgrado", "Direccion informacion academica", "Division de registro y matricula", "Decanatura facultad", "Secretaria facultad" }));
        Selector.setSelectedItem(null);

        javax.swing.GroupLayout FormLayout = new javax.swing.GroupLayout(Form);
        Form.setLayout(FormLayout);
        FormLayout.setHorizontalGroup(
            FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormLayout.createSequentialGroup()
                .addGroup(FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(B_IniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(B_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FormLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Selector, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        FormLayout.setVerticalGroup(
            FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Selector, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201)
                .addGroup(FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_IniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        Selector.getAccessibleContext().setAccessibleName("");
        Selector.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        SIA.setFont(new java.awt.Font("Arial", 1, 105)); // NOI18N
        SIA.setForeground(new java.awt.Color(96, 25, 25));
        SIA.setText("S I A");

        LogoUNAL.setForeground(new java.awt.Color(96, 25, 25));
        LogoUNAL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/UNALpeq.png"))); // NOI18N

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EncabezadoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(LogoUNAL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SIA, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SIA, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogoUNAL, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_IniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_IniciarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_IniciarSesionActionPerformed

    private void B_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_SalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_SalirActionPerformed

    private void EncabezadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EncabezadoKeyPressed
        
    }//GEN-LAST:event_EncabezadoKeyPressed

    private void EncabezadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EncabezadoMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_EncabezadoMousePressed

    private void EncabezadoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EncabezadoMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_EncabezadoMouseDragged

    private void B_SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_SalirMouseClicked
        Login log = new Login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_B_SalirMouseClicked

    private void B_IniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_IniciarSesionMouseClicked
        seleccionarRol(Selector.getSelectedItem().toString().toLowerCase());
    }//GEN-LAST:event_B_IniciarSesionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RolSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RolSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RolSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RolSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RolSelect("a","b").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_IniciarSesion;
    private javax.swing.JButton B_Salir;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JPanel Fondo;
    private loginsia.PanelRound Form;
    private javax.swing.JLabel LogoUNAL;
    private javax.swing.JLabel SIA;
    private javax.swing.JComboBox<String> Selector;
    private javax.swing.JLabel Usuario;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    private void seleccionarRol(String rol) {
        rol.trim();
        String SQL = "SET ROLE '"+rol+"'";
        try {            
            Statement st = conexion.createStatement();
            st.executeQuery(SQL);
            if ("estudiante".equals(rol)) {
                SIA sia = new SIA(this.usuario,this.contrasena);
                sia.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null,"Por el momento, no hay acceso a estos roles. Estamos trabajando en ello.");
            }
            
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null,"Error: Usted no tiene acceso a este rol. Pruebe ingresando a otro.");
        }
    }

    /*private void validarUsuario(String usuario, String contrasena) {
        int resultado = 0;
        String SQL = "select * from vinculado where vin_usuario = '"+usuario+"' and vin_contrasena = '"+contrasena+"'";
        try {
            
            Statement st = conexion.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            System.out.println(usuario);
            System.out.println(contrasena);
            if (rs.next()) {
                
                resultado = 1;
                if (resultado == 1) {
                    SeleccionarRol form = new SeleccionarRol();
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null,"Error de acceso, usuario no registrado");
            }
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error "+e.getMessage());
        }
    }*/
}
